services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /path/to/traefik.toml:/traefik.toml
      - /path/to/traefik_dynamic.toml:/traefik_dynamic.toml
      - /path/to/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

networks:
  web:
    external: true
